/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LongFormRouteImport } from './routes/long-form'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalysisToolRouteImport } from './routes/analysis-tool'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanResultRouteImport } from './routes/scan_.result'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as KSlugRouteImport } from './routes/k.$slug'
import { Route as CheckoutDeepAnalysisRouteImport } from './routes/checkout.deep-analysis'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LongFormRoute = LongFormRouteImport.update({
  id: '/long-form',
  path: '/long-form',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisToolRoute = AnalysisToolRouteImport.update({
  id: '/analysis-tool',
  path: '/analysis-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultRoute = ScanResultRouteImport.update({
  id: '/scan_/result',
  path: '/scan/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KSlugRoute = KSlugRouteImport.update({
  id: '/k/$slug',
  path: '/k/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDeepAnalysisRoute = CheckoutDeepAnalysisRouteImport.update({
  id: '/checkout/deep-analysis',
  path: '/checkout/deep-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis-tool': typeof AnalysisToolRoute
  '/login': typeof LoginRoute
  '/long-form': typeof LongFormRoute
  '/monitoring': typeof MonitoringRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/survey': typeof SurveyRoute
  '/checkout/deep-analysis': typeof CheckoutDeepAnalysisRoute
  '/k/$slug': typeof KSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/scan/result': typeof ScanResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis-tool': typeof AnalysisToolRoute
  '/login': typeof LoginRoute
  '/long-form': typeof LongFormRoute
  '/monitoring': typeof MonitoringRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/survey': typeof SurveyRoute
  '/checkout/deep-analysis': typeof CheckoutDeepAnalysisRoute
  '/k/$slug': typeof KSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/scan/result': typeof ScanResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis-tool': typeof AnalysisToolRoute
  '/login': typeof LoginRoute
  '/long-form': typeof LongFormRoute
  '/monitoring': typeof MonitoringRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/survey': typeof SurveyRoute
  '/checkout/deep-analysis': typeof CheckoutDeepAnalysisRoute
  '/k/$slug': typeof KSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/scan_/result': typeof ScanResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis-tool'
    | '/login'
    | '/long-form'
    | '/monitoring'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/scan'
    | '/settings'
    | '/survey'
    | '/checkout/deep-analysis'
    | '/k/$slug'
    | '/s/$slug'
    | '/scan/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis-tool'
    | '/login'
    | '/long-form'
    | '/monitoring'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/scan'
    | '/settings'
    | '/survey'
    | '/checkout/deep-analysis'
    | '/k/$slug'
    | '/s/$slug'
    | '/scan/result'
  id:
    | '__root__'
    | '/'
    | '/analysis-tool'
    | '/login'
    | '/long-form'
    | '/monitoring'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/scan'
    | '/settings'
    | '/survey'
    | '/checkout/deep-analysis'
    | '/k/$slug'
    | '/s/$slug'
    | '/scan_/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisToolRoute: typeof AnalysisToolRoute
  LoginRoute: typeof LoginRoute
  LongFormRoute: typeof LongFormRoute
  MonitoringRoute: typeof MonitoringRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SurveyRoute: typeof SurveyRoute
  CheckoutDeepAnalysisRoute: typeof CheckoutDeepAnalysisRoute
  KSlugRoute: typeof KSlugRoute
  SSlugRoute: typeof SSlugRoute
  ScanResultRoute: typeof ScanResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-form': {
      id: '/long-form'
      path: '/long-form'
      fullPath: '/long-form'
      preLoaderRoute: typeof LongFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-tool': {
      id: '/analysis-tool'
      path: '/analysis-tool'
      fullPath: '/analysis-tool'
      preLoaderRoute: typeof AnalysisToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan_/result': {
      id: '/scan_/result'
      path: '/scan/result'
      fullPath: '/scan/result'
      preLoaderRoute: typeof ScanResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$slug': {
      id: '/k/$slug'
      path: '/k/$slug'
      fullPath: '/k/$slug'
      preLoaderRoute: typeof KSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/deep-analysis': {
      id: '/checkout/deep-analysis'
      path: '/checkout/deep-analysis'
      fullPath: '/checkout/deep-analysis'
      preLoaderRoute: typeof CheckoutDeepAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisToolRoute: AnalysisToolRoute,
  LoginRoute: LoginRoute,
  LongFormRoute: LongFormRoute,
  MonitoringRoute: MonitoringRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SurveyRoute: SurveyRoute,
  CheckoutDeepAnalysisRoute: CheckoutDeepAnalysisRoute,
  KSlugRoute: KSlugRoute,
  SSlugRoute: SSlugRoute,
  ScanResultRoute: ScanResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
